#!/bin/sh

wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/update-course-template \
           https://raw.githubusercontent.com/jncraton/course-template/master/.gitignore \
           https://raw.githubusercontent.com/jncraton/course-template/master/formats.md \
           https://raw.githubusercontent.com/jncraton/course-template/master/readme-template.md \
           https://raw.githubusercontent.com/jncraton/course-template/master/head.tex \
           https://raw.githubusercontent.com/jncraton/course-template/master/makefile \
           https://raw.githubusercontent.com/jncraton/course-template/master/reference.docx \
           https://raw.githubusercontent.com/jncraton/course-template/master/requirements.txt \
           https://raw.githubusercontent.com/jncraton/course-template/master/runtime.md \
           https://raw.githubusercontent.com/jncraton/course-template/master/head.md \
           https://raw.githubusercontent.com/jncraton/course-template/master/tail.md \
           https://raw.githubusercontent.com/jncraton/course-template/master/style.css
          
chmod 755 update-course-template
