#!/bin/sh

wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/update-syllabus-template
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/readme-template.md
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/head.tex
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/makefile
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/reference.docx
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/requirements.txt
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/runtime.md
wget -q -N https://raw.githubusercontent.com/jncraton/course-template/master/style.css
